version: '3.8'

services:
  spark-master:
    image: spark:3.5.7
    container_name: master
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: [ "/opt/spark/sbin/start-master.sh", "-h", "spark-master" ]
    ports: [ "7077:7077", "8080:8080" ]

  spark-worker-1:
    image: spark:3.5.7
    container_name: worker_1
    depends_on: [ "spark-master" ]
    command: [ "/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077" ]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    cpus: "1.0"
    mem_limit: 600m
  spark-worker-2:
    image: spark:3.5.7
    container_name: worker_2
    depends_on: [ "spark-master" ]
    command: [ "/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077" ]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    cpus: "1.0"
    mem_limit: 600m

  spark-client:
    image: spark:3.5.7
    container_name: client
    depends_on: [ "spark-master", "spark-worker-1", "spark-worker-2" ]
    working_dir: /opt/app
    volumes:
      - ./learn_spark:/opt/app
    command: [ "bash", "-lc", "sleep infinity" ]
